export interface Publication {
    year: number;
    title: string;
    authors: string;
    venue: string;
    abstract: string;
    links: {
      arxiv?: string;
      openreview?: string;
      pdf?: string;
    };
  }
  
  export const publications: Publication[] = [
    {
      year: 2026,
      title: "DeepWeightFlow: Re-Basined Flow Matching for Generating Neural Network Weights",
      authors: "Saumya Gupta, Scott Biggs, Moritz Laber, Zohair Shafi, Robin Walters, Ayan Paul",
      venue: "ICLR 2026",
      abstract:
        "Building efficient and effective generative models for neural network weights has been a research focus of significant interest that faces challenges posed by the high-dimensional weight spaces of modern neural networks and their symmetries. Several prior generative models are limited to generating partial neural network weights, particularly for larger models, such as ResNet and ViT. Those that do generate complete weights struggle with generation speed or require finetuning of the generated models. In this work, we present DeepWeightFlow, a Flow Matching model that operates directly in weight space to generate diverse and high-accuracy neural network weights for a variety of architectures, neural network sizes, and data modalities. The neural networks generated by DeepWeightFlow do not require fine-tuning to perform well and can scale to large networks.",
      links: {
        arxiv: "https://arxiv.org/abs/2601.05052",
        openreview: "https://openreview.net/forum?id=fOwsr1VTi8",
        pdf: "https://arxiv.org/pdf/2601.05052",
      },
    },
    // Add future publications above this line (newest first)
  ];